version: '3.8'

services:
  app:
    build: .
    container_name: contest-system-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - contest-network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run migrate && npm run seed && npm start"
    # command: sh -c "npm start"

networks:
  contest-network:
    driver: bridge